name: 'Docker Build And Push to registry GitHub Action'
description: 'Docker Build And Push to registry GitHub Action'
inputs:
  version:
    description: 'Target Docker version'
    required: true
  username:
    description: 'username'
    required: true
  token:
    description: 'token'
    required: true
  registryurl:
    description: 'registryurl'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to docker registry if private registry
      run: |
        if [ ${{ inputs.username }} ]
        then
          sudo docker login registry.gitlab.com -u ${{ inputs.username }} -p ${{ inputs.token }}
        fi
      shell: bash
    - name: Build Docker Image
      id: docker_build_step
      run: |
        tag=${GITHUB_REF#refs/heads/}.$(git rev-parse --short HEAD)

        docker build . --target cli -t ${{ inputs.registryurl }}/cli:${{ inputs.version }}
        docker build . --target cron -t ${{ inputs.registryurl }}/cron:${{ inputs.version }}
        docker build . --target fpm_server -t ${{ inputs.registryurl }}/fpm_server:${{ inputs.version }}
        docker build . --target web_server -t ${{ inputs.registryurl }}/web_server:${{ inputs.version }}

        echo "::set-output name=tag::$tag"
      shell: bash
    - name: Push Docker Image
      run: |
        docker push ${{ inputs.registryurl }}/cli:${{ inputs.version }}
        docker push ${{ inputs.registryurl }}/cron:${{ inputs.version }}
        docker push ${{ inputs.registryurl }}/fpm_server:${{ inputs.version }}
        docker push ${{ inputs.registryurl }}/web_server:${{ inputs.version }}
      shell: bash